import type { Metadata } from "next";
import {
  Bricolage_Grotesque,
  DM_Serif_Display,
  Google_Sans,
} from "next/font/google";
import "./globals.css";
import AuthProvider from "@/components/AuthProvider";

const googleSans = Google_Sans({
  subsets: ["latin"],
});

const dmSerif = DM_Serif_Display({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-serif",
});

const bricolageGrotesque = Bricolage_Grotesque({
  subsets: ["latin"],
  variable: "--font-bricolage-grotesque",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${googleSans.className} ${bricolageGrotesque.variable} ${dmSerif.variable} antialiased`}
      >
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
