import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";

const manrope = DM_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manrope.className} antialiased max-w-4xl mx-auto`}>
        {children}
      </body>
    </html>
  );
}
